import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";

const Home: NextPage = ({ results }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Rijksmuseum!</a>
        </h1>

        <p className={styles.description}>
          {results && (
            <Image
              src={results.artObjects[0].headerImage.url}
              alt=""
              width={600}
              height={200}
            />
          )}
        </p>
      </main>
    </div>
  );
};

export async function getServerSideProps() {
  const response = await fetch(
    `https://www.rijksmuseum.nl/api/nl/collection?key=${process.env.API_KEY_RIJKMUSEUM}&involvedMaker=Rembrandt+van+Rijn`
  );

  const data = await response.json();

  console.log(data);

  return {
    props: {
      results: data,
    },
  };
}

export default Home;
